return {
    { import = "plugins.ui.tabline" },
    { import = "plugins.ui.statusline" },
    { import = "plugins.ui.telescope" },
    { import = "plugins.ui.whichkey" },
    { import = "plugins.ui.zen" },
    { import = "plugins.ui.noice" },
    { import = "plugins.ui.dashboard" },
    { import = "plugins.ui.explorer" },
    { import = "plugins.ui.terminal" },
    { import = "plugins.ui.gitsigns" },
    { import = "plugins.ui.hydra" },
    { import = "plugins.ui.window-select" },
    { import = "plugins.ui.quickfix" },
}